<CiscoIPPhoneGraphicMenu>
    <LocationX>-1</LocationX>
    <LocationY>-1</LocationY>
    <Width><?=$cipImage->getWidth();?></Width>
    <Height><?=$cipImage->getHeight();?></Height>
    <Depth>2</Depth>
    <Data><?=$cipImage->getCipData();?></Data>
    <SoftKeyItem>
        <Name>Dial</Name>
        <URL>Key:Speaker</URL>
        <Position>1</Position>
    </SoftKeyItem>
</CiscoIPPhoneGraphicMenu>